### ISSUE TITLE
Return to previous page failes

### ISSUE THREAD

**Issue by Greyhat-Mubee** [sorodeji/work-tools#11]
Hi Orodeji,
I noticed clicking on the previous page arrow button to go back one page does not seem to work perfectly.  I think its something you might need to work on.

**Comment by s-orodeji** [comment]
Branch created for this issue

**Comment by Greyhat-Mubee** [comment]
Hi Orodeji, Got your update
However, i noticed after successful login, there is no session time out or login expiry. 
You might need to work on that.

**Comment by s-orodeji** [comment]
Hello,
Implementing session timeout is a bit complicated and will require me to change how I am currently storing states 
I will consider it but i am not making any promises

**Comment by s-orodeji** [comment]
This issue is now resolved I will suggest opening a different issue for the session timeout problem
